# Generated by Django 3.2.15 on 2022-12-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_hotpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hot', to='blog.post'),
        ),
    ]
