# Generated by Django 3.2.15 on 2023-01-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230113_0010'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='created_at',
        ),
    ]
